### ISSUE TITLE
Adoptium Temurin?

### ISSUE THREAD

**Issue by famod** [joschi/setup-jdk#25]
AdoptOpenJDK is basically history, although they say:
> For a limited period of time we will augment the current AdoptOpenJDK API to serve binaries built from the Eclipse Adoptium community (Hotspot builds) and IBM (OpenJ9 builds). When you ask the current AdoptOpenJDK API for the latest ‘hotspot’ build by ‘adoptopenjdk’ we will serve you the latest Temurin build, and when you ask for the ‘openj9’ build by ‘adoptopenjdk’ we will serve you the IBM build. The licenses and content of these builds are unchanged. Although arguably that behavior is incorrect for the query, we think that is what most people would expect to get during the transition.

https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

So I guess it's time to switch over to (or add) https://adoptium.net/

**Comment by joschi** [comment]
@famod Thanks for bringing this up!

Once https://github.com/actions/setup-java/pull/201 has been reviewed and merged, I would actually see https://github.com/actions/setup-java/ as the natural "successor" of `joschi/setup-jdk`.

The migration is straight forward (only add the `distribution` property) and the official `setup-java` action now also supports AdoptOpenJDK and (hopefully soon) Eclipse Temurin.

**Comment by famod** [comment]
@joschi thanks for the pointer, going to track actions/setup-java#201 then!

**Comment by joschi** [comment]
@famod I'll probably also release a (final) version 3.0.0 of this action which switches from the AdoptOpenJDK API to the Adoptium API.

The recommended action going forward would still be https://github.com/actions/setup-java/ then. 😃

**Comment by karlhorky** [comment]
Would it make sense to put a deprecation notice + migration guide in the readme for `joschi/setup-jdk`?

Eg. What would be the way to upgrade this config to use `actions/setup-java`?

```
      - name: Install Java JDK
        uses: joschi/setup-jdk@v1
        with:
          java-version: 'openjdk8'
          architecture: 'x64'
        env:
          # https://github.com/actions/toolkit/issues/641#issuecomment-728963957
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
```
